-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "priceCheckedOn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "priceSource" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "batteryCapacity" DROP NOT NULL,
ALTER COLUMN "weightGrams" DROP NOT NULL;
